---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: covid-analysis
  namespace: spark-jobs
  labels:
    app: spark
    analysis: covid-19
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster

  image: spark-covid-analysis:latest
  imagePullPolicy: Never  # Use local Minikube image

  mainApplicationFile: local:///opt/spark/work-dir/covid_analysis.py

  sparkVersion: "3.5.0"

  restartPolicy:
    type: Never

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: "3.5.0"
      component: driver
    serviceAccount: spark

  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: "3.5.0"
      component: executor
